### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-auto-revive#6]
The module keeps spamming this lol

-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)
-> Not found option 'AutoRevive.Enable'. The default value is used (No)

**Comment by locus313** [comment]
made some updates for the config that might solve this:
https://github.com/azerothcore/mod-auto-revive/pull/9
When I tested after making the config updates I didn't see this spam in the console. I did my test with docker on centos7

**Comment by pangolp** [comment]
I just tested the module, in the latest version and the message no longer appears, as far as I believe, it was solved in pull request 9, which is mentioned above. But this topic was never linked, which remains open.
